[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."

[functions]
  included_files = [
    "node_modules/surgio/**",
    "node_modules/@surgio/**",
    "provider/**",
    "template/**",
    "*.js",
    "*.json",
    "surgio/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true
