'use strict';


module.exports = {
    type: 'custom',
    nodeList: [{
        "nodeName": "🇨🇳 台湾 CHT [01]",
        "type": "vmess",
        "hostname": "cht1.qiangdong.xyz",
        "port": "153",
        "uuid": "0b7ed047-bf54-34c2-9cde-23e54dff2fc0",
        "alterId": "64",
        "method": "auto",
        "udp-repay": true,
        "network": "ws",
        "path": "/api/v3/download.getFile",
        "ws-headers": {
            "Host": "4786589416.laowanxiang.com",
        },
    },
        {
            "nodeName": "🇨🇳 台湾 CHT [02]",
            "type": "vmess",
            "hostname": "cht2.qiangdong.xyz",
            "port": "153",
            "uuid": "4e87f851-37cc-3b49-9cb5-6582985dc68a",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇨🇳 台湾 CHT [03]",
            "type": "vmess",
            "hostname": "cht3.qiangdong.xyz",
            "port": "153",
            "uuid": "09e2b227-e05c-3bc9-9ad6-89f17405ad57",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇨🇳 台湾 CHT [04]",
            "type": "vmess",
            "hostname": "cht4.qiangdong.xyz",
            "port": "153",
            "uuid": "2c84d7bc-a1fc-37dd-b9db-fcd0b4709dc8",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇨🇳 台湾 CHT [05]",
            "type": "vmess",
            "hostname": "cht5.qiangdong.xyz",
            "port": "153",
            "uuid": "80ef6c0f-fa4c-3618-b23a-e45775bfbde8",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇨🇳 台湾 Seed",
            "type": "vmess",
            "hostname": "seed1.qiangdong.xyz",
            "port": "153",
            "uuid": "f6e7430e-d190-3678-bbbd-f72b7980551b",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇯🇵 日本 5G [01]",
            "type": "vmess",
            "hostname": "54.199.233.160",
            "port": "153",
            "uuid": "f92834d1-64c0-3e72-bb02-d8e5f5694e4d",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇯🇵 日本 5G [02]",
            "type": "vmess",
            "hostname": "52.198.234.76",
            "port": "153",
            "uuid": "563d7ad4-62d2-3340-a570-1d1345ed7783",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇯🇵 日本 5G [03]",
            "type": "vmess",
            "hostname": "18.179.196.86",
            "port": "153",
            "uuid": "541e0099-db2f-386d-80fb-74baf31be0b6",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇯🇵 日本 HC",
            "type": "vmess",
            "hostname": "61.152.72.136",
            "port": "153",
            "uuid": "17221d38-b585-308a-a6a0-2f4f2aee7eb4",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇯🇵 日本 KDDI",
            "type": "vmess",
            "hostname": "211.9.220.55",
            "port": "153",
            "uuid": "165a168f-fb20-3057-8dd6-23e25246c3a9",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 5G",
            "type": "vmess",
            "hostname": "15.254.2.249",
            "port": "153",
            "uuid": "5f9bccd1-1c46-3199-99b4-993f1a994264",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 Azure",
            "type": "vmess",
            "hostname": "13.66.191.60",
            "port": "153",
            "uuid": "e2d2529b-067a-3aa3-a47c-7152a85fb6f2",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 GIA [01]",
            "type": "vmess",
            "hostname": "154.17.21.43",
            "port": "153",
            "uuid": "d813e7c5-41da-3d9d-aa6b-08304e8365e5",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 GIA [02]",
            "type": "vmess",
            "hostname": "154.17.21.45",
            "port": "153",
            "uuid": "83c5a337-d036-317a-a55a-7e057a886e05",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 GIA [03]",
            "type": "vmess",
            "hostname": "154.17.0.20",
            "port": "153",
            "uuid": "d8eebf4a-072e-3e83-91b8-537ae2a69b7c",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 HE [01]",
            "type": "vmess",
            "hostname": "5.188.202.20",
            "port": "153",
            "uuid": "58c2ce59-8e55-3363-9466-ac3fcf1b5e7a",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇺🇸 美国 HE [02]",
            "type": "vmess",
            "hostname": "5.188.202.30",
            "port": "153",
            "uuid": "8f9a46eb-4f05-360a-9a02-6af5991ae47b",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇭🇰 香港 HA",
            "type": "vmess",
            "hostname": "cioaskle12cx.0tk8a3a1q4t94dler.com",
            "port": "153",
            "uuid": "9d8c88a1-122c-3c4d-bd5c-a627acf06ade",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇭🇰 香港 HC [01]",
            "type": "vmess",
            "hostname": "120.77.207.169",
            "port": "153",
            "uuid": "31040946-aea3-36c7-a78d-7346f61c0a25",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇭🇰 香港 HC [02]",
            "type": "vmess",
            "hostname": "120.79.39.85",
            "port": "153",
            "uuid": "2d1a068a-5c44-39b0-bb7f-5ebbf76b4a67",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
        {
            "nodeName": "🇭🇰 香港 WTT",
            "type": "vmess",
            "hostname": "wtt1.qiangdong.xyz",
            "port": "153",
            "uuid": "18b7f5ee-39f6-3e7d-8804-46c8f6cda8e1",
            "alterId": "64",
            "method": "auto",
            "udp-repay": true,
            "network": "ws",
            "path": "/api/v3/download.getFile",
            "ws-headers": {
                "Host": "4786589416.laowanxiang.com",
            },
        },
]
}